---
title: "cell_cycle"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cell_cycle}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/cell_cycle/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

```{r setup}
library("GimmmeMySC")
library("Seurat")

path <- file.path(
  dirname(getwd()),
  "inst",
  "extdata"
)
source(file.path(path, "conf.R"))
```

```{r}
load(file.path(path, "integrated_bcells2.rda"))
```

## Data normalization
```{r}
DefaultAssay(seurat) <- "RNA"
seurat <- NormalizeData(seurat) %>%
    FindVariableFeatures() %>%
    ScaleData() %>%
  RunPCA(features = c(cc.genes$s.genes, cc.genes$g2m.genes) %>% func_format())

plot_dim_cycle(seurat)
seurat_subset <- subsampling_sc(seurat)
plot_dim_cycle0(seurat_subset, split.by = "Type")
plot_dim_cycle0(seurat_subset, split.by = "Patient")
```

## Cell cycle regression
```{r, eval = FALSE}
seurat <- ScaleData(
  seurat,
  vars.to.regress = c("S.Score", "G2M.Score"),
  features = rownames(seurat)
)
```

```{r}
seurat <- RunPCA(
  seurat,
  features = c(cc.genes$s.genes, cc.genes$g2m.genes) %>%
    func_format()
)
plot_dim_cycle(seurat)
seurat_subset <- subsampling_sc(seurat)
plot_dim_cycle0(seurat_subset, split.by = "Type")
plot_dim_cycle0(seurat_subset, split.by = "Patient")
```

```{r}
seurat <- RunPCA(
  seurat,
  features = VariableFeatures(seurat),
  reduction_key = "Dim. ",
  npcs = max_dim
)
```

## Save data
```{r, eval = FALSE}
save(seurat, file = file.path(path, "integrated_bcells2.rda"))
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
