---
title: "Data integration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_integration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r config, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/data_integration/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

```{r setup, message = FALSE}
library("GimmmeMySC")
library("GimmeMyPlot")
library("Seurat")
library("rlist")
library("RColorBrewer")
library("cowplot")
library("kableExtra")
library("readxl")

n_dim <- 30
pal_discrete_sc <- palette_discrete()[-7]

path <- file.path(
  dirname(getwd()),
  "inst",
  "extdata"
)
path_fig <- file.path(dirname(getwd()), "vignettes", "figures", "data_integration")

source(file.path(path, "conf.R"))
```

```{r}
load(file.path(path, "wt_bcell_cycle.rda"))
wt <- seurat
load(file.path(path, "ko_bcell_cycle.rda"))
ko <- seurat
```

# Transfer learning
```{r}
wt@meta.data[, "labels"] <- Idents(wt)
wt@assays$SCT@scale.data <- matrix()
ko@assays$SCT@scale.data <- matrix()
seurat <- merge(wt, y = ko)
```

## Learning
```{r}
anchors <- FindTransferAnchors(
    reference = wt,
    query = seurat,
    # normalization.method = "SCT",
    reference.reduction = "pca",
    # reference.reduction = integration_method,
    dims = seq(n_dim)
)
```

```{r}
wt2 <- RunUMAP(
  wt,
  dims = seq(n_dim),
  # reduction = integration_method,
  reduction = "pca",
  return.model = TRUE
)
```

## Transfering
```{r}
seurat <- MapQuery(
    anchorset = anchors,
    query = seurat,
    reference = wt2,
    refdata = list(labels = "labels"),
    # reference.reduction = integration_method,
    reduction.model = "umap"
)
```

```{r}
cl_trans <- TransferData(
    anchorset = anchors,
    dims = seq(n_dim),
    # weight.reduction = KO[[integration_method]],
    refdata = Idents(wt)
  )
seurat <- AddMetaData(seurat, metadata = cl_trans)

save(seurat, file = file.path(path, "integr_bcell_cycle.rda"))
```

```{r}
load(file.path(path, "integr_bcell_cycle.rda"))
seurat <- reorder_idents(seurat)
seurat_old <- seurat
plot_dim(seurat, cols = pal_discrete_sc)
```

```{r, fig.height = 2, fig.width = 2}
plot_dim(seurat, cols = pal_discrete_sc, alpha = .1, label.size = 8) + 
  NoLegend() +
  theme(
    plot.margin = unit(c(0, 0, 0, 0), "cm"),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )
```

## UMAP per Type
```{r}
seurat_subset <- subsampling_sc(seurat, group.by = "Type")

plot_dim(
  object = seurat_subset,
  split.by = 'Type',
  col = pal_discrete_sc
) + NoLegend()

bar_ident_group(
  seurat_subset, 
  group.by = "Type", 
  idents = "predicted.labels"
)

bar_group_ident(
  seurat_subset,
  group.by = "Type",
  idents = "predicted.labels",
  colour = pal_discrete_sc
)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
data("l_bcell_markers")
plot_marker_split(seurat, l_bcell_markers)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
data("jcb_markers")
plot_marker_split(seurat, jcb_markers)
```

## Cell per cluster
```{r}
seurat <- subset(
    seurat_old, 
    subset = Type == "KO"
)

seurat <- reorder_idents(seurat, "RNA_snn_res.0.35")
plot_dim(
    seurat, 
    split.by = "RNA_snn_res.0.35",
    col = pal_discrete_sc,
    pt.size = .25,
    ncol = 4,
    label = FALSE
) + NoLegend()

Idents(seurat) <- "predicted.labels"
plot_dim(
    seurat, 
    split.by = "predicted.labels",
    col = pal_discrete_sc,
    pt.size = .25,
    ncol = 4,
    label = FALSE
) + NoLegend()
```

```{r}
reorder_idents(seurat, y = "RNA_snn_res.0.35") %>%
  plot_dim(cols = pal_discrete_sc)
seurat <- reorder_idents(seurat)
seurat_old <- seurat
plot_dim(seurat, cols = pal_discrete_sc)
```

## Scores
```{r, message = FALSE, fig.height = 6, fig.width = 12}
plot_sc_violin(
    seurat,
    features = paste0("prediction.score.", levels(Idents(seurat))),
    nrow = 2,
    ncol = 5
)
```

## Confusing table
```{r, fig.width = 3.7}
confusing_table(seurat, as_percent = FALSE)
confusing_table(seurat)
confusing_table(seurat, margin = 2)
```

## Cell markers
### From microarray
```{r, message = FALSE}
plot_module(seurat, jcb_markers)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
plot_ident_celltype(seurat)
```

## Misclassified
```{r, message = FALSE, fig.height = 6, fig.width = 12}
l_seurat <- list.map(
    levels(Idents(seurat)),
    f(x) ~ {
      res <- subset(seurat, idents = x)
      Idents(res) <- "RNA_snn_res.0.35"
      return(res)
    }
)

p <- list.map(
    l_seurat,
    f(x, y, z) ~ plot_dim(x, pt.size = 1) +
      ggtitle(z)
)

plot_grid(plotlist = p, ncol = 3, nrow = 2, align = "hv")
plot_grid(plotlist = p[8:length(p)], ncol = 3, nrow = 2, align = "hv")
```

```{r}
tmp <- list.map(
    l_seurat,
    f(x, y, z) ~cluster_size(Idents(x))  %>%
     rbind("Total" = c(n = colSums(.[, "n", drop = FALSE]), freq = "")) %>% 
        rownames_to_column(var = "Group") %>%
        mutate(Cluster = z)
    ) %>%
     list_rbind()


cluster_counts <- tmp %>% 
  count(Cluster) %>% 
  pull(n)

group_names <- paste("Cluster", unique(tmp$Cluster))

p <- tmp %>% 
    select(-Cluster) %>%
    kable_sc()  %>%
  pack_rows(
    index = setNames(cluster_counts, group_names),
    label_row_css = "background-color: #666; color: #fff;"
  )
save_kable(
    p,
    file = file.path(path_fig, "table_cells.png"),
    zoom = 2
)
p
```

```{r}
cluster_marker_genes0 <- list.map(
  l_seurat,
  f(x, y, z) ~ {
      cts <- AverageExpression(
            x,
            assay = assay,
            slot = "data",
            return.seurat = FALSE
        ) %>% 
          pluck(assay) %>%
          as.data.frame() %>% 
          rename_with(~ str_remove(., "^g")) %>%
          mutate(gene = rownames(.))

    FindConservedMarkers(
     x,
    ident.1 = "1",
    grouping.var = "Patient",
    assay = assay,
    # grouping.var = "Type",
    logfc.threshold = .Machine$double.xmin
  ) %>%
    mutate(
      cluster = z,
      gene = rownames(.),
      log2FoldChange = rowMeans(select(., ends_with("avg_log2FC")), na.rm = TRUE),
      padj = rowMeans(select(., ends_with("p_val_adj")), na.rm = TRUE),
      `pct.1` = rowMeans(select(., ends_with("pct.1")), na.rm = TRUE),
      `pct.2` = rowMeans(select(., ends_with("pct.2")), na.rm = TRUE)
    ) %>%
  left_join(set_colnames(cts, c("exp.1", "exp.2", "gene")), by = "gene")
  }
)
cluster_marker_genes <- list.rbind(cluster_marker_genes0)
min_p <- cluster_marker_genes %>%
  filter(padj > 0) %>%
  summarise(min_padj = min(padj)) %>%
  pull(min_padj)

cluster_marker_genes$padj[which(cluster_marker_genes$padj == 0)] <- min_p
```

```{r}
top50 <- list.map(
  l_dea, 
  f(x) ~ x %>%
  slice_head(n = 50)
)

p <- list.map(
  top50,
  f(x, y, z) ~ plot_dot(
    l_seurat[[z]],
    features = x %>% pull("gene") %>% unique()
  ) +
    labs(title = z)
)
plot_grid(plotlist = p, nrow = 2, align = "hv")

p2 <- list.map(
  top50,
  f(x, y, z) ~ plot_feature(
        l_seurat[[z]],
        features = x %>% pull("gene") %>% unique(),
        reduction = "ref.umap",
        slot = "data",
        cols = brewer.pal(9, "Reds")
    ) %>%
        theme_multiple(ncol = 3, nrow = 2, title = z)
)

p3 <- list.map(
    top50,
    f(x, y, z) ~ 
        plot_violin_sc(
            object = l_seurat[[z]],
            features = x %>% pull("gene") %>% unique(),
            slot = "data",
            assay = assay
        ) %>%
        theme_multiple(ncol = 3, nrow = 2, title = z)
)
```
```{r}
p2 <- list.rbind(top50) %>% 
    pull("gene") %>% 
    unique() %>%
    plot_feature(
        seurat,
        features = .,
        reduction = "ref.umap",
        cols = brewer.pal(9, "Reds")
    )
 plot_grid(plotlist = p2, ncol = 4, nrow = 3)
```

## Pseudo-bulk
```{r}
# seurat$cell_type <- Idents(seurat) %>% 
  # fct_relevel(as.character(0:9))
cts <- AggregateExpression(
  seurat,
  group.by = c("predicted.labels", "Patient"),
  assay = "RNA",
  slot = "counts",
  return.seurat = FALSE
)

cts <- as.data.frame(cts$RNA)
cts <- list.map(
  levels(seurat@meta.data[, "predicted.labels"]),
  f(x) ~{
    select(cts, starts_with(paste0("g", x, "_"))) %>% 
      set_colnames(colnames(.) %>% str_remove_all(paste0("g", x, "_")))
  }
) %>% set_names(levels(seurat@meta.data[, "predicted.labels"]))

cell_pct <- pct_by_ident_type(seurat) %>%
    rownames_to_column("gene_name")
```

### Differential analysis
```{r}
library(DESeq2)

metadata_samples <- colnames(cts[[1]]) %>%
    data.frame(id = ., condition = str_remove_all(., "\\d*$") %>% str_remove_all(., "_$")) %>%
    mutate(across(everything(), as.factor)) %>%
    column_to_rownames("id")
metadata_samples$condition <- relevel(metadata_samples$condition, ref = "KO")

genome_version <- 113
if (species == "human") {
    genome_species <- "hsapiens"
} else {
  genome_species <- "mmusculus"
}

data("biomart_annotation", package = "GimmeMyOmics")
annotation <- biomart_annotation[[paste(genome_species, genome_version, sep = "_")]]

l_dea_proc <- list.map(
    names(cts),
    f(name_cl) ~{
        gene_count_raw  <- pluck(cts, name_cl) %>%
            rownames_to_column("gene_name")
        
        metadata_genes <- filter(annotation, !duplicated(ensembl_gene_id)) %>%
            left_join(gene_count_raw, ., by = "gene_name") %>%
            select(colnames(annotation))
        
        gene_count <- pluck(cts, name_cl) %>%
            round()
        
        dea_df <- DESeqDataSetFromMatrix(
            countData = gene_count,
            colData = metadata_samples,
            design = ~ condition
        ) %>%
            .[rowSums(counts(.) >= 10) >= 3, ]
        
        dea <- DESeq(dea_df, quiet = TRUE)
        
        dea_raw <- lfcShrink(
            dea,
            contrast = c(colnames(metadata_samples)[1], levels(pull(metadata_samples, 1))),
            type = "ashr",
            quiet = TRUE
        )
        
        dea_pretty <- format_dea(
            dea_raw,
            metadata_genes,
            fc_threshold = fc_threshold,
            p_threshold = p_threshold,
            name_id = "gene_name"
        ) %>%
            mutate(
                Expression = ifelse(
                    gene_name %in% cell_pct$gene_name[cell_pct[[paste0(name_cl, ".WT")]] > pct_threshold] |
                        gene_name %in% cell_pct$gene_name[cell_pct[[paste0(name_cl, ".KO")]] > pct_threshold],
                    Expression,
                    "ns"
                )
            )
    }
)
```

### Dotplot
```{r}
l_deg0 <- list.map(
    l_dea_proc, 
    f(x) ~x %>% 
        mutate(description = "") %>%
        print_dea() %>%
        select(-`Full name`)
)
l_deg <- l_deg0 %>% discard(~ nrow(.x) == 0)
top10 <- list.map(
    l_deg,  
    f(x, xx, xxx) ~head(x, 10) %>%
        mutate(cluster = xxx)) %>%
    list.rbind() %>%
    rename(gene = "Gene") %>%
    filter(!duplicated(gene))

last_row_numbers <- top10 %>%
    mutate(row_num = row_number()) %>%
    group_by(cluster) %>%
    slice_tail(n = 1) %>%
    pull(row_num) %>%
    sort()
plot_dot(
    seurat, 
    features = pull(top10, "gene"),
    # group.by = "cell_type",
    split.by = "Type"
) +
    geom_vline(xintercept = last_row_numbers + 0.5) +
    geom_hline(yintercept = seq(2, (length(l_deg0) -1) * 2, by = 2) + 0.5)
```

### Marker plots
```{r}
l_bcell_markers <- list.map(l_deg, pull(., Gene) %>% unique())
plot_marker_split(seurat, l_bcell_markers, n_lines = length(l_deg0))
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
