---
title: "Differential expression"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{differential_expression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r config, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/differential_expression/",
  fig.width = 12,
  fig.height = 6,
  dpi = 300
)
```

```{r setup, message = FALSE}
library(GimmeMyOmics)
library(GimmmeMySC)
library(GimmeMyPlot)
library(magrittr)
library(rlist)
library(Seurat)
library(cowplot)
library(kableExtra)
library(openxlsx)

path <- file.path(
  dirname(getwd()),
  "inst",
  "extdata"
)
path_fig <- file.path(dirname(getwd()), "vignettes", "figures", "differential_expression")

source(file.path(path, "conf.R"))

fc_threshold  <- log2(1.5)
p_threshold <- .05
pct_threshold <- 0.25
exp_threshold <- 0.1

# grouping.var <- "Type"
grouping.var <- NULL
cell_label <- paste0(
    assay,
    "_snn_res.",
    0.35
)
# cell_label <- "predicted.labels"
split.by <- NULL
# split.by <- "Type"

pseudo <- TRUE
pal_discrete_sc <- palette_discrete()[-7]
```

```{r}
load(file.path(path, "integrated_bcells4.rda"))
best_resolution <- 0.35
snn_cluster <- paste0(
    assay,
    "_snn_res.",
    best_resolution
)

Idents(seurat) <- snn_cluster
```

## Differentially Expressed Genes
```{r}
# ids <- data.frame(
#     id.1 = c(6, 3, 3, 3, 0, 0, 4, 5, 5),
#     id.2 = c(2, 2, 6, 0, 1, 4, 1, 1, 4)
# )

if (isFALSE(pseudo)) {
  ids <- NULL
  cluster_marker_genes <- dea_sc(seurat, ids, grouping.var = grouping.var)
  
  l_dea_raw <- cluster_marker_genes %>%
    mutate(gene_name = gene) %>%
    format_dea(fc_threshold = fc_threshold, p_threshold = p_threshold)
  
  l_dea_proc <- dea2deseq(l_dea_raw, pct_threshold = pct_threshold, exp_threshold = exp_threshold)
}
```

# Pseudo-bulk
```{r}
if (isTRUE(pseudo)) {
library("DESeq2")

cts <- AggregateExpression(
  seurat,
  group.by = c(cell_label, "Patient"),
  assay = "RNA",
  slot = "counts",
  return.seurat = FALSE
)

cts <- pluck(cts, assay) %>%
  as.data.frame()
cts <- list.map(
  levels(seurat@meta.data[, cell_label]),
  f(x) ~{
    select(cts, starts_with(paste0("g", x, "_"))) %>% 
      set_colnames(colnames(.) %>% str_remove_all(paste0("g", x, "_")))
  }
) %>% set_names(levels(seurat@meta.data[, cell_label]))

cell_pct <- pct_by_ident_type(seurat) %>%
    rownames_to_column("gene_name")

metadata_samples <- colnames(cts[[1]]) %>%
    data.frame(id = ., condition = str_remove_all(., "\\d*$") %>% str_remove_all(., "_$")) %>%
    mutate(across(everything(), as.factor)) %>%
    column_to_rownames("id")
metadata_samples$condition <- relevel(metadata_samples$condition, ref = "KO")

genome_version <- 113
if (species == "human") {
    genome_species <- "hsapiens"
} else {
  genome_species <- "mmusculus"
}

data("biomart_annotation", package = "GimmeMyOmics")
annotation <- biomart_annotation[[paste(genome_species, genome_version, sep = "_")]]

l_dea_proc <- list.map(
    names(cts),
    f(name_cl) ~{
        gene_count_raw  <- pluck(cts, name_cl) %>%
            rownames_to_column("gene_name")
        
        metadata_genes <- filter(annotation, !duplicated(ensembl_gene_id)) %>%
            left_join(gene_count_raw, ., by = "gene_name") %>%
            select(colnames(annotation))
        
        gene_count <- pluck(cts, name_cl) %>%
            round()
        
        dea_df <- DESeqDataSetFromMatrix(
            countData = gene_count,
            colData = metadata_samples,
            design = ~ condition
        ) %>%
            .[rowSums(counts(.) >= 10) >= 3, ]
        
        dea <- DESeq(dea_df, quiet = TRUE)
        
        dea_raw <- lfcShrink(
            dea,
            contrast = c(colnames(metadata_samples)[1], levels(pull(metadata_samples, 1))),
            type = "ashr",
            quiet = TRUE
        )
        
        dea_pretty <- format_dea(
            dea_raw,
            metadata_genes,
            fc_threshold = fc_threshold,
            p_threshold = p_threshold,
            name_id = "gene_name"
        ) %>%
            mutate(
                Expression = ifelse(
                    gene_name %in% cell_pct$gene_name[cell_pct[[paste0(name_cl, ".WT")]] > pct_threshold] |
                        gene_name %in% cell_pct$gene_name[cell_pct[[paste0(name_cl, ".KO")]] > pct_threshold],
                    Expression,
                    "ns"
                ),
                gene = gene_name
            )
    }
)
}
```

## Volcano plots
```{r, message = FALSE, fig.height = 5, fig.width = 10}
l_deg <- l_dea_proc %>% discard(~ nrow(.x) == 0)
kable_dea(l_deg, file = file.path(path_fig, "table_dea.png"))

l_deg_top <- list.map(
  l_deg,
  f(x) ~ top_genes(
    x,
    fc_threshold = fc_threshold,
    p_threshold = p_threshold,
    n = 15
  )
)

p <- volcano_sc(
  l_deg,
  top_genes = l_deg_top,
  fc_threshold = fc_threshold,
  p_threshold = p_threshold
)

n <- length(p)
plot_grid(plotlist = p[seq(ceiling(n/2))], align = "hv", nrow = 2)
plot_grid(plotlist = p[(ceiling(n/2) + 1):n], align = "hv", nrow = 2)
```

# Save DEG
```{r}
if (isFALSE(pseudo)) {
  metadata <- TRUE
} else {
  metadata <- FALSE
}

l_deg2 <- list.map(
    l_deg,
    f(x) ~ {
      if (!pseudo) {
        x <- mutate(x, description = "")
      }
      x %>%
        print_dea(metadata = metadata, f = desc, rank_by = "rank_fc") %>%
        mutate(Expression = if_else(`Fold-change` > 0, "up", "down")) %>%
        split(.$Expression)
    }
) %>%
    set_names(names(l_deg)) %>%
    list_flatten(name_spec = "{outer}_{inner}")

omics2excel(
  l_deg2,
    file = file.path(path_fig, "deg.xlsx"),
    function(x) {
      res <- select(x, -Expression)
      if (!pseudo)
        select(res, -`Full name`)
      else
        res
    }
)

if (isFALSE(pseudo))
omics2excel(
  l_deg2,
  file = file.path(path_fig, "marker_cluster.xlsx"),
  function(x) {
    x %>%
    select(-c(c("ensembl_gene_id", "Full name", "gene"), contains(c("KO_", "WT_", "val")))) %>%
    rename(
      `avg_log2FC` = "Fold-change",
      p_val_adj = "P-adjusted"
    ) %>%
    select(-contains("exp."))
  }
)
```

```{r}
gene_lists <- list.map(l_deg_top, pull(., "gene_name") %>% sort())
custom_upset_barplot(gene_lists, ratio = 1)
custom_upset_barplot(gene_lists, ratio = 1, only_intersect = "inverse")

l_deg_top_all <- list.map(
  l_deg,
  f(x) ~ top_genes(
    x,
    fc_threshold = fc_threshold,
    p_threshold = p_threshold,
    return_rank = TRUE
  )
)

list.map(
    l_deg_top_all,
    ~pull(., "gene_name") %>% 
    sort()
  ) %>%
  custom_upset_barplot(ratio = 1, top_n  = 20)
```

## Enrichment
```{r, eval = FALSE}
if (species == "human") {
  org_lib <- "org.Hs.eg.db"
} else {
    org_lib <- "org.Mm.eg.db"
}
library(org_lib, character.only = TRUE)
filter <- dplyr::filter
select <- dplyr::select
rename <- dplyr::rename
```

### ORA
```{r, eval = FALSE}
l_ora <- list.map(
  l_dea,
  f(x) ~enrichGO(
    gene = pull(x, "gene_name"),
    OrgDb = get(org_lib),
    keyType = "ALIAS",
    ont = "ALL",
    pvalueCutoff = 1,
    qvalueCutoff = 1,
    universe = Features(seurat)
  )
)
```

```{r, eval = FALSE}
list.map(
    l_ora ,
    f(x, y, z) ~ {
      plot_enrich(
        x,
        cex = 0.65,
        label_x = "generatio",
        method = "ora",
        # regex = pathway_keywords()$immunity_additional,
        n = 15,
        title = z,
        name_id = "GeneRatio"
      )
    }
) %>% 
  compact() %>%
  plot_grid(plotlist = ., ncol = 2, nrow = 2, align = "hv")

list.map(l_ora, f(i) ~print_enrich(i, method = method) %>% nrow()) %>%
    list.cbind() %>%
    set_rownames("# Pathway GO") %>%
    kable0()

list.map(
  l_ora,
  f(i, j, k) ~ {
    tmp <- print_enrich(
      i, 
      regex = pathway_keywords()$immunity_additional
    )
    if (nrow(tmp) > 1)
  heatmap_enrich_full(
    l_ora[[j]],
    l_dea[[j]],
    regex = pathway_keywords()$immunity_additional,
    width_text = 100
  ) + labs( title = paste("Cluster", k), y = NULL, x = NULL) +
     theme_custom()
  }
) %>%
  compact() %>%
  plot_grid(plotlist = ., ncol = 2, nrow = NULL, align = "hv")
 

omics2excel(
  l_ora, 
  file = file.path(path, "ora.xlsx"), 
  func = function(x) print_enrich(x, method = "ora")
)
```

### GSEA
```{r, eval = FALSE}
var <- "gene_name"

l_deg_ranked <- list.map(
    l_dea_proc,
    f(x) ~ {
        metric <- "log2FoldChange"
        de_genes_ranked <- top_genes(x, 0.01, 1, n = Inf) %>% #, rank = TRUE) %>%
            # mutate(ranked_padj = sign(log2FoldChange) * (log10(padj))) %>%
            pull(metric, name = var) %>%
            sort(decreasing = TRUE) %>%
            .[!is.na(names(.))] %>%
            .[is.finite(.)] %>%
            .[!duplicated(.)]
    }
)

l_gsea <- list.map(
    l_deg_ranked,
    f(x) ~ {
        gseGO(
            x,
            ont = "ALL",
            OrgDb = get(org_lib),
            keyType = "ALIAS",
            verbose = FALSE
        ) %>%
            # setReadable(org_lib, 'ENSEMBL') %>%
            suppressWarnings() %>%
            invisible()
    }
)
```

```{r, eval = FALSE}
list.map(
    l_gsea,
    f(x, y, z) ~ {
      plot_enrich(
        x,
        cex = 0.65,
        label_x = "NES",
        method = "gsea",
        # regex = pathway_keywords()$immunity_additional,
        n = 15,
        title = z
      )
    }
) %>%
  compact() %>%
  plot_grid(plotlist = ., ncol = 2, nrow = 2, align = "hv")

list.map(l_gsea, f(i) ~print_enrich(i, method = "gsea") %>% nrow()) %>%
    list.cbind() %>%
    set_rownames("# Pathway GO") %>%
    kable0()

omics2excel(
  l_gsea, 
  file = file.path(path, "gsea.xlsx"), 
  func = function(x) print_enrich(x, method = "gsea")
)
```

```{r, eval = FALSE}
list.map(
    l_gsea,
    f(i, j, k) ~ {
        tmp <- print_enrich(
            i,
            method = "gsea",
            regex = pathway_keywords()$immunity_additional
        )
        if (nrow(tmp) > 1)
            heatmap_enrich_full(
                l_gsea[[j]],
                l_dea[[j]],
                method = "gsea",
                regex = pathway_keywords()$immunity_additional,
                width_text = 100
            ) + labs( title = paste("Cluster", k), y = NULL, x = NULL) +
            theme_custom()
    }
)  %>%
    compact() %>%
    plot_grid(plotlist = ., ncol = 2, nrow = NULL, align = "hv")
```

## Dotplots
```{r}
top50 <- list.map(
    l_deg_top_all,  
    f(x, xx, xxx) ~head(x, 50) %>%
        mutate(cluster = xxx)) %>%
    list.rbind()

top5_filtered <- top50 %>%
    filter(!duplicated(gene_name)) %>%
    group_by(cluster) %>%
    slice_head(n = 5) %>%
    ungroup()
```

```{r, eval = FALSE}
if (!pseudo) {
  last_row_numbers <- top5_filtered %>%
      # ungroup() %>%
      mutate(row_num = row_number() %>% rev()) %>%
      # mutate(row_num = row_number()) %>% # if pseudo
      group_by(cluster) %>%
      slice_tail(n = 1) %>%
      pull(row_num) %>%
      sort()
  
  DoHeatmap(
      seurat,
      features = top10$gene,
      # group.by = "cell_type_na",
      group.colors = palette_discrete(),
      slot = "data"
  ) + 
      NoLegend() + 
      scale_fill_gradientn(
          colors = brewer.pal(11, "Spectral"),
          na.value = "black"
      ) +
      geom_hline(yintercept = last_row_numbers[-1] - 0.5, color = "black", linetype = "solid", linewidth = 1)
}
```

```{r}
if (pseudo) {
  plot_dot2(seurat, top5_filtered, split.by = "Type", cols = rev(pal_discrete_sc[seq(2)])) +
    geom_hline(yintercept = seq(2, (length(l_dea_proc) - 1) * 2, by = 2) + 0.5)
} else {
  plot_dot2(seurat, top5_filtered)
}
```

```{r}
markers <- top50  %>%
    split(.$cluster) %>%
    list.map(~pull(., gene_name) %>% unique())

if (pseudo) {
  plot_marker_split(seurat, markers, normalize = TRUE, n_line = length(l_dea_proc), cols = rev(pal_discrete_sc[seq(2)]))
  } else {
  plot_mfeature(seurat, markers, nrow = 3)
  plot_markers(seurat, markers)
}
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
