---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{get_started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r config, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/get_started/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

## Setup
```{r}
library("GimmmeMySC")
library("GimmeMyPlot")
library("Seurat")
library("rlist")
library("clustree")
library("magrittr")
library("harmony")

source(
  file.path(file.path(
  dirname(getwd()),
  "inst",
  "extdata"
), "conf.R"))

if (split.by != "Patient") {
  integration_method <- "RPCA"
} else {
  integration_method <- "Harmony"
}
if (assay == "ATAC") {
  slot <- "data"
} else {
  slot <- "scale.data"
}
```

## Load data
```{r}
load(file.path(path_data, paste0(seurat_dataset, ".rda")))
# seurat@assays$SCT@scale.data <- matrix()
if (integrated & split.by == "Patient")
  seurat <- subset(seurat, subset = Type == target_type)
DefaultAssay(seurat) <- assay2
```

## PCA
### Dimension selection
```{r message=FALSE, warning=FALSE}
if (assay == "ATAC") {
  library("Signac")
  seurat <- RunTFIDF(seurat)
  seurat <- FindTopFeatures(seurat, min.cutoff = "q0")
  seurat <- RunSVD(seurat, n = max_dim)
  
  plot_cor_depth(seurat)
}
if (!cell_cycle && (multiome || assay2 == "RNA")){
  # VariableFeatures(seurat) <- setdiff(
  #   VariableFeatures(seurat),
  #   "Pcdh9"
  # )
  # if (split.by == "Type") {
      DefaultAssay(seurat) <- "RNA"
      seurat[["RNA"]] <- as(seurat[["RNA"]], Class = "Assay5")
      seurat[["RNA"]] <- JoinLayers(seurat[["RNA"]])
      seurat[["RNA"]] <- split(
        seurat[["RNA"]],
        f = seurat[[]][, split.by],
        layers = c("counts", "data")
    )
      if (isFALSE(SCT)) {
      seurat <- NormalizeData(seurat) %>%
        FindVariableFeatures() %>%
        ScaleData()
      } else {
        seurat <- SCTransform(seurat)
      }
      seurat <- RunPCA(
        seurat,
        # features = VariableFeatures(seurat),
        npcs = max_dim
      )
  # }
  DefaultAssay(seurat) <- assay
}
```

```{r}
eig <- seurat[[reduction]]@stdev / sum(seurat[[reduction]]@stdev) * 100
plot_pca_qc(eig)

cumsum(eig) %>% .[n_dim] %>% round(1)
cumsum(eig) %>% .[. < 80] %>% last() %>% round(1)
```

```{r, fig.height = 6, fig.width = 12}
list.map(
  list(seq(15), 16:30, 31:45),
  ~DimHeatmap(seurat, dims = ., cells = 500, balanced = TRUE, reduction = reduction, assays = assay, slot = slot)
)
```

```{r}
comp_genes <- list.map(
    dims,
    f(x) ~ Loadings(seurat, reduction = reduction) %>%
        as.data.frame() %>%
        set_colnames(str_replace(colnames(.), "(\\w+)_(\\d+)", "PC_\\2")) %>%
        select(paste0("PC_", x)) %>%
        arrange(abs(!!sym(paste0("PC_", x)))) %>%
        tail(20) %>%
        rownames()
) %>% set_names(dims)

if (assay == "ATAC") {
  plot_cor_depth(seurat)
  dims <- filter_depth_cor(seurat) %>% head(n_dim)
} else {
  list.map(
    lapply(cc.genes, func_format),
    f(i) ~lapply(comp_genes, function(x) x[x %in% func_format(i)]) %>% compact()
  ) %>% set_names(c("G2/M", "S"))
}
```

### Component markers
```{r pca_plot, fig.height = 6}
print(seurat[[reduction]], dims = 1:5, nfeatures = 5)
VizDimLoadings(seurat, dims = 1:2, reduction = reduction)
```

## UMAP before
```{r umap}
gc()
seurat <- RunUMAP(
  seurat, 
  dims = dims,
  reduction.key = "Dim. ",
  reduction = reduction
  )
```

```{r}
Idents(seurat) <- split.by
plot_dim(
  seurat,
  label = FALSE
)
plot_dim(
  seurat,
  split.by = split.by,
  label = FALSE
) + NoLegend()
```

## Integration
```{r}
seurat <- integrate_layers(seurat, integration_method, assay, split.by, reduction, dims)

eig <- seurat[[integration_method]]@stdev / sum(seurat[[integration_method]]@stdev) * 100
plot_pca_qc(eig)

cumsum(eig) %>% .[n_dim] %>% round(1)
cumsum(eig) %>% .[. < 80] %>% last() %>% round(1)
```

```{r, fig.height = 6, fig.width = 12}
list.map(
  list(seq(15), 16:30, 31:45),
  ~DimHeatmap(seurat, dims = ., cells = 500, balanced = TRUE, reduction = integration_method, assays = assay, slot = slot)
)

if (assay == "ATAC") {
  dims <- filter_depth_cor(seurat) %>% head(n_dim)
}
```

```{r}
if (multiome) {
  assay_inv <- ifelse(assay2 == "ATAC", "RNA", "ATAC")
  orig.reduction <- ifelse(assay2 == "ATAC", "pca", "lsi")
  new.reduction <- paste0(integration_method, str_to_lower(assay_inv), sep = ".")
  DefaultAssay(seurat) <- assay_inv
  # seurat[["RNA"]] <- split(
  #     seurat[["RNA"]],
  #     f = seurat[[]][, split.by],
  #     layers = c("counts", "data")
  # )
  if (assay_inv == "ATAC") {
  seurat@assays[["ATAC_v5"]] <- CreateAssay5Object(
    counts = seurat@assays$ATAC$counts, 
    data = seurat@assays$ATAC$data
  )
  seurat@assays[["ATAC_v5"]]@key <- "atacv5_"
  
  DefaultAssay(seurat) <- "ATAC_v5"
  seurat <- ScaleData(seurat)
  seurat[["ATAC_v5"]] <- split(
    seurat[["ATAC_v5"]], 
    f = seurat[[]][, split.by],
    layers = c("counts","data")
  )
  seurat <- IntegrateLayers(
    object = seurat,
    method = integration_method2,
    new.reduction = new.reduction,
    orig.reduction = orig.reduction,
    dims.to.integrate = seq(n_dim),
    verbose = TRUE,
    assay = "ATAC_v5",
    features = Features(seurat@assays[["ATAC_v5"]])
  )
} else {
  seurat <- IntegrateLayers(
      object = seurat,
      method = integration_method2,
      new.reduction = new.reduction,
      orig.reduction = orig.reduction,
      dims.to.integrate = seq(n_dim),
      verbose = TRUE,
      normalization.method = ifelse(SCT, "SCT", "LogNormalize")
  )
    seurat[["RNA"]] <- as(seurat[["RNA"]], Class = "Assay5")
    seurat[["RNA"]] <- JoinLayers(seurat[["RNA"]])
}
  
  if (assay == "ATAC") {
    dims_inv <- filter_depth_cor(seurat) %>% head(n_dim)
  } else {
    dims_inv <- seq(n_dim)
  }
  
  seurat <- RunUMAP(
      seurat, 
      dims = dims_inv,
      reduction = paste(integration_method, str_to_lower(assay_inv), sep = "."),
      reduction.name = paste0(str_to_lower(assay_inv), ".umap")
  )
  DefaultAssay(seurat) <- assay2
}
```

## UMAP
```{r}
if (multiome){
  reduction.name <- paste(str_to_lower(assay), "umap", sep = ".")
} else {
  reduction.name <- "umap"
}
seurat <- RunUMAP(
  seurat, 
  dims = dims,
  reduction = integration_method,
  reduction.name = reduction.name
)
```

```{r}
plot_dim(
    seurat,
    label = FALSE
)
plot_dim(
    seurat,
    split.by = split.by,
    label = FALSE
) + NoLegend()
```

## Clustering
```{r clus_int}
resolution2 <- seq(.1, .4, 0.05)
resolution <- c(seq(.5, 1, by = 0.1), 1.2, 1.5)
resolution_tot <- c(resolution2, resolution)
```

```{r}
if (multiome) {
  reduction <- "wnn.umap"
  seurat <- FindMultiModalNeighbors(
    object = seurat,
    # reduction.list = list("pca", "lsi"),
    reduction.list = list("Harmony.rna", "Harmony"),
    dims.list = list(seq(n_dim), seq(n_dim)),
    modality.weight.name = "wnn.weight",
    verbose = TRUE
  ) %>%
  RunUMAP(
    nn.name = "weighted.nn", 
    reduction.name = reduction2, 
    reduction.key = "wnnUMAP_"
  )
  graph_name <- "wsnn"
  prefix_cl <- "wsnn_res."
} else {
  seurat <- FindNeighbors(
    seurat,
    reduction = integration_method, 
    dims = dims
  )
  graph_name <- tail(names(seurat@graphs), 1)
  prefix_cl <- paste0(assay, "_snn_res.")
}

seurat <- FindClusters(
  seurat,
  verbose = FALSE,
  algorithm = 3,
  resolution = resolution_tot,
  graph.name = graph_name
)
```


```{r}
seurat2 <- seurat
cols_to_remove <- paste0(prefix_cl, resolution[-1])
seurat2@meta.data <- seurat2@meta.data[, !colnames(seurat2@meta.data) %in% cols_to_remove]

select(seurat@meta.data, contains(prefix_cl)) %>%
     list.mapv(f(x) ~ levels(x) %>% length()) %>% 
    set_names(names(.) %>% str_remove(prefix_cl)) %>%
  plot_bar_sc0(label_y = "value", sort = "desc")
```

```{r}
clusters <- grep(prefix_cl, colnames(seurat[[]]), value = TRUE) %>% sort()
kable_cluster(
  seurat,
  clusters, 
  file = file.path(path_fig, "clusters.png"),
  assay = assay
)
grep(prefix_cl, colnames(seurat2[[]]), value = TRUE) %>% sort() %>%
  kable_cluster(
    seurat,
    ., 
    file = file.path(path_fig, "clusters2.png"),
    assay = assay
)
```

```{r, fig.width = 20, fig.height = 10}
clustree_sc(seurat, prefix_cl, clusters)
```

```{r, fig.width = 16, fig.height = 8}
clustree_sc(seurat2, prefix_cl, clusters)
```

```{r, fig.height = 5, fig.width = 10}
plot_res(seurat, clusters, reduction = reduction2)
plot_res(
  seurat, 
  clusters[c(3, 5, 6, 8)],
  ncol = 2, 
  reduction = reduction2
  )
plot_res(
  seurat,
  clusters,
  cols = scales::hue_pal(), 
  reduction = reduction2
)
```

# Markers
```{r, message = FALSE, fig.height = 6, fig.width = 12}
DefaultAssay(seurat) <- "RNA"
data("jcb_markers")
plot_mfeature(seurat, jcb_markers, nrow = 3, cluster = FALSE, reduction = reduction2)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
data("l_bcell_markers")
plot_mfeature(seurat, l_bcell_markers, nrow = 3, cluster = FALSE, reduction = reduction2)
```

## Save data
```{r}
if (assay == "ATAC") {
  DefaultAssay(seurat) <- "ATAC"
   seurat@assays$ATAC_v5 <- NULL
}

Idents(seurat) <- seurat[[]][, snn_cluster]
if (integrated && split.by == "Patient") {
  save(seurat, file = file.path(path_data, paste0(seurat_dataset, "_", target_type, ".rda")))
} else {
  save(seurat, file = file.path(path_data, paste0(seurat_dataset, "c.rda")))
}
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
