---
title: "multimodal_integration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{multimodal_integration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/multimodal/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

```{r setup}
library("GimmmeMySC")
library("GimmeMyPlot")
library("GimmeMyOmics")
library("Seurat")
library("Signac")
library("rlist")
library("magrittr")

source(
  file.path(file.path(
  dirname(getwd()),
  "inst",
  "extdata"
), "conf.R"))

SCT <- FALSE
integration_method <- "RPCA"
fc_threshold  <- log2(1.5)
p_threshold <- .05
```

## Data
```{r}
# load(file.path(path_root, "rna_bcell_integrated7abcde.rda"))
load(file.path(path_root, "rna_bcell_integrated5.rda"))
# load(file.path(path_root, "rna_bcell_wt.rda"))
seurat$labels <- seurat@meta.data[, "SCT_snn_res.0.35"] -> Idents(seurat)
seurat <- subset(
    seurat,
    idents = c("8", "9"),
    invert = TRUE
)
seurat$modality <- "RNA"
DefaultAssay(seurat) <- "RNA"
rna <- RunUMAP(
  seurat,
  dims = dims,
  reduction = integration_method,
  return.model = TRUE
)
```

```{r}
load(file.path(path_root, "atac_bcell_integrated3.rda"))
atac1 <- seurat
load(file.path(path_root, "atac_bcell_integrated5.rda"))
seurat@assays$ATAC_v5 <- NULL
Idents(seurat) <- seurat@meta.data[, "ATAC_snn_res.0.35"] -> seurat$labels
seurat <- subset(
    seurat,
    idents = c("6", "7"),
    invert = TRUE
)
# load(file.path(path_root, "atac_bcell_wt2.rda"))
# seurat$labels <- seurat@meta.data[, "RNA_snn_res.0.15"]
seurat <- reorder_idents(seurat, "labels")
seurat$modality <- "ATAC"
DefaultAssay(seurat) <- "RNA"
atac <- seurat -> atac_old
gc()
```

```{r, eval = FALSE}
options(future.globals.maxSize = 5 * 1024^3)
# seurat <- subset(seurat, subset = Type == target_type)

DefaultAssay(seurat) <- "RNA"
seurat[["RNA"]] <- split(
  seurat[["RNA"]],
  f = seurat[[]][, "Type"],
  layers = c("counts", "data")
)
# seurat <- SCTransform(seurat)#, vars.to.regress = c("S.Score", "G2M.Score"))
seurat <- NormalizeData(seurat) %>%
  FindVariableFeatures() %>%
  ScaleData()
seurat <- RunPCA(seurat, npcs = max_dim)#, features = VariableFeatures(seurat))

seurat <- IntegrateLayers(
    object = seurat,
    method = get(paste0(integration_method, "Integration")),
    new.reduction = integration_method,
    orig.reduction = reduction,
    dims.to.integrate = dims,
    normalization.method = ifelse(SCT, "SCT", "LogNormalize"),
    verbose = TRUE
)
seurat[["RNA"]] <- JoinLayers(seurat[["RNA"]])

resolution2 <- seq(.1, .4, 0.05)
resolution <- c(seq(.5, 1, by = 0.1), 1.2, 1.5)
resolution_tot <- c(resolution2, resolution)
seurat <- FindNeighbors(
  seurat,
  reduction = integration_method, 
  dims = dims
)

seurat <- FindClusters(
  seurat,
  verbose = FALSE,
  algorithm = 3,
  resolution = resolution_tot,
  graph.name = tail(names(seurat@graphs), 1)
)
seurat <- RunUMAP(
  seurat, 
  dims = dims,
  reduction = integration_method
)

# DefaultAssay(seurat) <- "RNA"
# seurat <- NormalizeData(seurat) %>%
#     FindVariableFeatures() %>%
#     ScaleData()

save(seurat, file = file.path(path_root, "atac_bcell_integrated5.rda"))
```

## Learning
```{r}
rna@assays$SCT@scale.data <- matrix()
# atac@assays$SCT@scale.data <- matrix()

load("/shared/projects/immunaid/data/dobino_1124/rna_bcell_integrated7abcd_clustering_markers.rda")
l_deg_top <- l_deg %>%
  .[!names(.) %in% c("8", "9")] %>%
  list.map(
  f(x) ~ top_genes(
    x,
    fc_threshold = fc_threshold,
    p_threshold = p_threshold,
    n = Inf,
    return_rank  = TRUE
  ) %>%
    filter(log2FoldChange > 0)
)
features <- list.map(l_deg_top, pull(., "gene_name") %>% head(500) %>% sort()) %>% unlist() %>% unique()

# features <- SelectIntegrationFeatures(
#   object.list = list(rna, atac),
#   nfeatures = 3000,
#   assay = c("RNA", "RNA")
# )
```

## Anchors
```{r}
anchors <- FindTransferAnchors(
  reference = rna,
  query = atac,
  query.assay = "RNA",
  normalization.method = ifelse(SCT, "SCT", "LogNormalize"),
  reference.reduction = integration_method,
  # reduction = tolower(integration_method),
  features = features,
  dims = dims,
  # k.filter = NA,
  k.anchor = 50
)
```

```{r}
anchor_df <- slot(anchors, "anchors") %>% as.data.frame()
(n_anchors <- nrow(anchor_df))
100 * length(
    unique(anchor_df[, 1])
) / ncol(rna)
100 * length(
    unique(anchor_df[, 2])
) / ncol(atac)

ggplot(anchor_df, aes(x = score)) +
  geom_histogram(bins = 50) +
  geom_vline(xintercept = 0.5, linetype = "dashed")

anchor_df <- filter(anchor_df, score > 0.5)
nrow(anchor_df)
nrow(anchor_df) / n_anchors * 100
```

```{r, eval = FALSE}
rna <- FindVariableFeatures(rna, nfeatures = 3000)
atac <- FindVariableFeatures(atac, nfeatures = 3000)

common_hvg <- intersect(VariableFeatures(rna), VariableFeatures(atac))
length(common_hvg)
```

```{r, eval = FALSE}
rna_expr <- GetAssayData(rna, assay = "RNA", layer = "data")[common_hvg, anchor_df$cell1]
atac_expr <- GetAssayData(atac, assay = "RNA", layer = "data")[common_hvg, anchor_df$cell2]

gene_cor <- sapply(common_hvg, function(g) {
  cor(rna_expr[g, ], atac_expr[g, ], method = "spearman")
})

gene_cor_df <- data.frame(gene = common_hvg, cor = gene_cor) %>%
  arrange(desc(cor))

ggplot(gene_cor_df, aes(x = cor)) + geom_histogram(bins = 50)

features_filtered <- gene_cor_df %>% 
  filter(cor > 0.1) %>% 
  pull(gene)

length(features_filtered)
```

```{r, eval = FALSE}
anchors2 <- FindTransferAnchors(
  reference = rna,
  query = atac,
  query.assay = "RNA",
  normalization.method = ifelse(SCT, "SCT", "LogNormalize"),
  reference.reduction = integration_method,
  # reduction = tolower(integration_method),
  features = features_filtered,
  dims = dims,
  # k.filter = NA,
  k.anchor = 50
)

anchor_df <- slot(anchors2, "anchors") %>% as.data.frame()

ggplot(anchor_df, aes(x = score)) +
  geom_histogram(bins = 50) +
  geom_vline(xintercept = 0.5, linetype = "dashed")
```

## Transfer
```{r}
atac <- MapQuery(
    anchorset = anchors,
    query = atac,
    reference = rna,
    refdata = list(labels = "labels"),
    reduction.model = "umap"
)

cl_trans <- TransferData(
    anchorset = anchors,
    dims = dims,
    refdata = Idents(rna)
  )
atac <- AddMetaData(atac, metadata = cl_trans)

atac_scores <- MappingScore(
    anchors = anchors,
    ndim = length(dims)
)
atac <- AddMetaData(
    object = atac,
    metadata = atac_scores,
    col.name = "mapping.score"
)

atac$predicted.labels <- factor(atac$predicted.labels, levels = levels(Idents(rna)))
Idents(atac) <- atac$predicted.labels

atac[["umap"]] <- CreateDimReducObject(
  embeddings = Embeddings(atac, "ref.umap"),
  key = "umap_",
  assay = DefaultAssay(atac)
)
rna[["umap"]] <- CreateDimReducObject(
    embeddings = Embeddings(rna, "umap"),
    key = "umap_",
    assay = "RNA"
)

DefaultDimReduc(rna) <- "umap"

seurat <- merge(rna, y = atac, merge.dr = TRUE)
seurat <- JoinLayers(seurat, assay = "RNA")
seurat$modality <- fct_relevel(seurat$modality, "RNA")
DefaultDimReduc(seurat) <- "umap"
```

## Plot
```{r}
plot_dim(seurat, split.by = "modality") +
  theme(strip.text = element_blank())
plot_dim(rna) + plot_dim(atac1)
plot_dim(rna) + plot_dim(atac_old)
plot_dim(seurat, group.by = "modality")

Idents(atac) %>%
  cluster_size() %>%
  kable_sc()

table(seurat$Patient, seurat$modality) %>% 
  rbind(Total = colSums(.)) %>% kable0()
```

## QC
### Prediction scores
```{r}
scores <- c("prediction.score.max", "mapping.score")
median_score <- map_dbl(
  scores,
  ~median(
    atac@meta.data[, .x],
    na.rm = TRUE
  )
)
median_score

p1 <- list.map(scores, f(x, y) ~plot_sc_violin(atac, features = x, ncol = 1, nrow = 1) + geom_hline(yintercept = median_score[[y]], linetype = "dashed", color = "black", lwd = 1) + ggtitle(NULL))
p2 <- plot_feature(
    atac,
    features = scores,
    reduction = "umap",
    # cluster = TRUE,
    prob = .7,
    label = TRUE
)
p1[[1]] | p2[[1]] + ggtitle(NULL)
p1[[2]] | p2[[2]] + ggtitle(NULL)

atac@meta.data %>%
    group_by(predicted.labels) %>%
    summarise(
        median_score = median(prediction.score.max),
        n = n()
    )

plot_sc_violin(
    atac,
    features = paste0("prediction.score.", levels(Idents(seurat))),
    nrow = 2,
    ncol = 4
)
```

### Confusion table
```{r}
old_ident <- "ATAC_snn_res.0.35"
new_ident <- "predicted.labels"
atac$ATAC_snn_res.0.35 <- factor(atac$ATAC_snn_res.0.35, levels = c("4", "3", "0", "1", "5", "2") %>% rev)
confusing_table(atac, new_ident = new_ident, old_ident = old_ident)
confusing_table(atac, new_ident = new_ident, old_ident = old_ident, margin = 2)
```

### Correlation
```{r}
rna.pb <- AggregateExpression(
    subset(seurat_rna, Type == "WT"),
    group.by = "labels"
)$RNA

atac.pb <- AggregateExpression(
    subset(seurat_atac, Type == "WT"),
    group.by = "predicted.labels"
)$RNA

common <- intersect(
    rownames(rna.pb),
    rownames(atac.pb)
)

plot_cor(
    rowMeans(rna.pb[common, ]),
    rowMeans(atac.pb[common, ]),
    method = "spearman"
) + 
  scale_x_log10() + 
  scale_y_log10() +
  labs(x = "RNA", y = "ATAC")
```

### Entropy
```{r}
score_cols <- grep(
    "^prediction.score.",
    colnames(seurat_atac@meta.data),
    value = TRUE
)

entropy <- apply(
    seurat_atac@meta.data[, score_cols],
    1,
    function(x) {
        x <- x / sum(x)
        -sum(x * log(x + 1e-12))
    }
)

seurat_atac$prediction_entropy <- entropy

plot_sc_violin(seurat_atac, features = "prediction_entropy", ncol = 1, nrow = 1)
plot_feature(
    seurat_atac,
    features = "prediction_entropy",
    reduction = "ref.umap"
)
```

## Session information
```{r end, echo = FALSE}
save(seurat, file = file.path(path_root, "integrated_bcell_wt2.rda"))
sessionInfo()
```
