---
title: "qc_analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{qc_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r config, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/qc_analysis/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

## Setup
```{r}
library("GimmmeMySC")
library("GimmeMyPlot")
library("Seurat")
library("rlist")
library("cowplot")

source(
  file.path(file.path(
  dirname(getwd()),
  "inst",
  "extdata"
), "conf.R"))

if (split.by != "Patient") {
  cell_label <- "cell_subtype_formatted"
} else {
  cell_label <- "cell_type_formatted"
}

if (assay != "ATAC") {
  features <- c("nFeature_RNA", "nCount_RNA", "percent_mitochondrial", "percent_ribosomal", "percent_hemoglobin")
} else {
  features <- c(
    paste0("nCount", "_", assay),
    paste0("nFeature", "_", assay),
    "nucleosome_signal",
    "TSS.enrichment",
    "percent_reads_in_peaks",
    "blacklist_ratio"
  )
}
```

```{r}
list_param <- load_dataset(path_data, seurat_dataset, split.by, target_type, pal_discrete_sc, pal_discrete_sc2, integrated, snn_cluster)
seurat <- format_celltype0(list_param$seurat, lim = 30)
seurat_subset <- format_celltype0(list_param$seurat_subset, lim = 30)
pal_discrete_sc <- list_param$pal_discrete_sc
pal_discrete_sc2 <- choose_palette(seurat, "cell_subtype_formatted2")
pal_discrete_sc3 <- choose_palette(seurat, "cell_type")
```

## Annotation (1)
```{r}
bar_group_ident(
    seurat,
    idents = "cell_subtype_formatted2",
    group.by = split.by,
    colour = pal_discrete_sc2
)
bar_group_ident(
    seurat,
    idents = snn_cluster,
    group.by = split.by,
    colour = pal_discrete_sc
)

list.map(
  unique(seurat_subset[[]][, split.by]),
  f(i) ~{
  tmp <- seurat_subset
  tmp[[]][, split.by][seurat_subset[[]][, split.by] != i] <- NA
  plot_dim(
    tmp,
    group.by = split.by,
    label = FALSE, 
    na.value = "grey", 
    reduction = reduction2
  ) +
    NoLegend() +
    ggtitle(i)
  }
)

plot_dim(
    seurat_subset,
    split.by = split.by,
    label = FALSE,
    cols = pal_discrete_sc,
    reduction = reduction2
) + NoLegend()
```

```{r}
bar_group_ident(
    seurat,
    idents = "cell_subtype_formatted2",
    group.by = "Patient",
    colour = pal_discrete_sc2
)
```

## UMAP
```{r}
plot_dim(
    seurat_subset,
    label = FALSE,
    cols = pal_discrete_sc, 
    reduction = reduction2
)
plot_dim(
    seurat_subset,
    split.by = "Patient",
    label = FALSE,
    cols = pal_discrete_sc,
    reduction = reduction2
) + NoLegend()
```

## QC
```{r, message = FALSE}
p <- plot_feature(seurat, pt.size = .25, features, reduction = reduction2) %>%
        list.map(f(x, y, z) ~x + ggtitle(str_clean(z)))
plot_grid(plotlist = p, nrow = 2, align = "hv")
```

## Cell cycle
```{r, fig.width = 5}
plot_dim_cycle(seurat_subset, reduction = reduction2)
```

```{r, message = FALSE}
Idents(seurat) <- "Phase"
Idents(seurat) %>% 
    cluster_size() %>%
    kable_sc(file = file.path(path_fig, "table_phase.png"))

plot_bar_sc(seurat)
```

## Annotation
### Main cell types
```{r}
Idents(seurat) <- cell_label
plot_bar_sc(seurat)

Idents(seurat) %>% 
    cluster_size() %>% 
    kable_sc(file = file.path(path_fig, "table_cells.png"))

plot_dim(seurat_subset, group.by = cell_label, col = pal_discrete_sc3, reduction = reduction2)
```

```{r, message = FALSE, fig.height = 5, fig.width = 10}
plot_dim_cell(
    seurat_subset,
    group.by = cell_label,
    split.by = cell_label,
    ncol = 3,
    label = FALSE,
    col = rep("black", 100),
    reduction = reduction2
) + NoLegend()
```

### B cells
```{r, message = FALSE, fig.width = 5}
cells <- WhichCells(seurat_subset, expression = cell_type_formatted == "B cell")
plot_dim_cell(seurat_subset, cols = pal_discrete_sc, cells = cells, group.by = "cell_subtype_formatted2", reduction = reduction2)
```

```{r, fig.height = 5, fig.width = 10}
subtypes_b <- seurat_subset[[]][cells, "cell_subtype_formatted"] %>% as.character() %>% unique()
seurat_subset$cell_subtype_formatted3 <- seurat_subset$cell_subtype_formatted
seurat_subset$cell_subtype_formatted3[!seurat_subset$cell_subtype_formatted3 %in% subtypes_b] <- NA
seurat_subset$cell_subtype_formatted3 <- fct_drop(seurat_subset$cell_subtype_formatted3)

plot_dim_cell(
    seurat_subset,
    group.by = "cell_subtype_formatted3",
    split.by = "cell_subtype_formatted3",
    cells = cells,
    label = FALSE,
    ncol = 3,
    cols = rep("black", 100), 
    reduction = reduction2
) +
    NoLegend()
```

### Cell subtypes
```{r}
Idents(seurat) <- "cell_subtype_formatted"
plot_bar_sc(seurat)
Idents(seurat) %>% 
    cluster_size() %>% 
    kable_sc(file = file.path(path_fig, "table_subcells.png"))
```

```{r, fig.width = 5}
plot_dim(seurat_subset, group.by = "cell_subtype_formatted", cols = pal_discrete_sc2, reduction = reduction2)
```

```{r, fig.height = 5, fig.width = 10}
top_cells <- seurat_subset$cell_subtype_formatted2 %>% fct_infreq() %>% levels() %>% head(12) %>% reorder_celltype()
seurat_subset$cell_subtype_formatted3 <- seurat_subset$cell_subtype_formatted2
seurat_subset$cell_subtype_formatted3[!seurat_subset$cell_subtype_formatted3 %in% top_cells] <- NA
Idents(seurat_subset) <- "cell_subtype_formatted3"
plot_dim_cell(
    seurat_subset,
    split.by = "cell_subtype_formatted3",
    label = FALSE,
    ncol = 3,
    cols = rep("black", 100), 
    reduction = reduction2
) +
    NoLegend()
```

```{r, fig.width = 5}
plot_dim_cell(seurat_subset, cols = pal_discrete_sc2, reduction = reduction2)
```

```{r, message = FALSE, fig.height = 5, fig.width = 10}
cell_categories <- seurat_subset$cell_type_formatted %>% unique() %>% na.omit()

list.map(
  cell_categories,
    f(x, y, z) ~ {
      cells <- WhichCells(seurat_subset, expression = cell_type_formatted == x)
      if(length(cells) > 50)
        plot_dim(
            seurat_subset,
            group.by = "cell_subtype_formatted",
            cells = cells,
            cols = rep(palette_discrete(), 5),
            pt.size = .25, 
            reduction = reduction2
        ) +
        labs(title = z, x = NULL)
    }
) %>% compact() %>%
plot_grid(plotlist = ., align = "hv", nrow = 2)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
cell_list <- map(cell_categories, ~ {
  seurat$cell_subtype[str_detect(seurat$cell_subtype, paste0("^", .x))] %>% na.omit() %>% keep_parenthesis()
}) %>%
  set_names(cell_categories) %>%
  .[order(lengths(.), decreasing = TRUE)]

p <- list.map(
  compact(cell_list),
  f(x, y, z) ~ plot_bar_sc(x, z)
)

n_max <- min(length(p), 9)
plot_grid(plotlist = p[seq(n_max)])
```

```{r, fig.height = 5, fig.width = 10}
Idents(seurat) <- cell_label
plot_sc_violin(
    seurat,
    nrow = 2,
    normalize = rep(10, length(features)),
    breaks = list(
      c(0, 1e3, 2.5e3, 5e3, 1e4),
      c(0, 1e3, 2.5e3, 5e3, 1e4),
      c(0.1, 0.5, 1, 2.5, 5, 10),
      c(0.1, 1, 5, 10, 25, 50, 1e3),
      c(0, 1, 10, 50),
      c(5e-3, 1e-2, 5e-2)
    ),
    features = features,
    col = pal_discrete_sc3
)
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
