---
title: "qc_cluster"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{qc_cluster}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/qc_cluster/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

```{r}
library("GimmmeMySC")
library("Seurat")
library("GimmeMyPlot")

source(
  file.path(file.path(
  dirname(getwd()),
  "inst",
  "extdata"
), "conf.R"))

cell_label <- "cell_subtype_formatted"
```

## Load data
```{r data}
load(file.path(path_data, paste0(seurat_dataset, ".rda")))

seurat_subset <- subsampling_sc(seurat) %>%
  subset(subset = Type == target_type)
  
if (split.by != "Type") {
  load(file.path(path_data, paste0(seurat_dataset, "_", target_type, ".rda")))
  seurat_subset <- subset(seurat, cells = Cells(seurat_subset))
  n_idents <- nlevels(Idents(seurat))
  if (n_idents > length(pal_discrete_sc))
    pal_discrete_sc <- palette_continuous()(n_idents)
}
seurat_subset$cell_subtype_formatted <-  fct_drop(seurat_subset$cell_subtype_formatted)

if (split.by == "Type") {
  seurat <- subset(
      seurat,
      subset = Type == target_type
  )
  seurat$cell_subtype_formatted <-  fct_drop(seurat$cell_subtype_formatted)
} else {
  pal_discrete_sc2 <- palette_continuous()(length(unique(seurat$cell_subtype_formatted)))
}
```

```{r}
lim <- 25
tab <- table(seurat$cell_subtype_formatted)
cell_types_low <- names(tab)[tab < lim]

seurat$cell_subtype_formatted2[seurat$cell_subtype_formatted2 %in% cell_types_low] <- NA

seurat$cell_subtype_formatted2 <- fct_drop(seurat$cell_subtype_formatted2)
```

## Clustering
```{r, clus_int_res}
Idents(seurat) %>% 
    cluster_size() %>%
    kable_sc(file = file.path(path_fig, "table_cell_cluster.png"))

plot_bar_sc(seurat)
```

```{r, fig.height = 2, fig.width = 2}
plot_dim(seurat, cols = pal_discrete_sc, alpha = .1, label.size = 8) + 
    NoLegend() +
    theme(
        plot.margin = unit(c(0, 0, 0, 0), "cm"),
        axis.text = element_blank(),
        axis.ticks = element_blank()
    )
```

```{r}
p2 <- plot_dim(seurat_subset, cols = pal_discrete_sc)
p2

p2 + plot_dim_cell(seurat_subset, group.by = "cell_subtype_formatted2", cols = pal_discrete_sc2)

plot_dim(
    seurat_subset,
    split.by = snn_cluster,
    cols = rep("black", 100),
    label = FALSE,
    ncol = 4
) + NoLegend()

plot_ident_celltype(seurat, cell_label = cell_label, col = pal_discrete_sc2)
Idents(seurat) <- "cell_subtype_formatted2"
plot_ident_celltype(seurat, cell_label = snn_cluster, col = pal_discrete_sc)
Idents(seurat) <- seurat[[]][, snn_cluster]

heatmap_celltype(seurat, snn_cluster, cell_label, as_percent = FALSE)
heatmap_celltype(seurat, snn_cluster, cell_label)
heatmap_celltype(seurat, snn_cluster, cell_label, margin = 2)
```

```{r, fig.height = 5, fig.width = 10}
plot_dim(
    seurat_subset,
    split.by = "cell_subtype_formatted2",
    cols = pal_discrete_sc,
    ncol = 3,
    combine = FALSE
)
```

```{r, fig.height = 5, fig.width = 10}
plot_dim(
    seurat_subset,
    split.by = "cell_type_formatted",
    ncol = 3,
    col = pal_discrete_sc
)
```

## Condition effect
```{r}
plot_dim(object = seurat_subset, group.by = "Patient")

bar_ident_group(
  seurat_subset,
  idents = snn_cluster
)

bar_group_ident(
  seurat_subset,
  idents = snn_cluster,
  colour = pal_discrete_sc
)
```

## QC
```{r, fig.height = 5, fig.width = 10}
plot_sc_violin(
    seurat,
    nrow = 2,
    normalize = c(10, 10, 10, 10, 10, 10),
    breaks = list(
      c(0, 1e3, 2.5e3, 5e3, 1e4),
      c(0, 1e3, 2.5e3, 5e3, 1e4),
      c(0.1, 0.5, 1, 2.5, 5, 10),
      c(0.1, 1, 5, 10, 25, 50, 1e3),
      c(0, 1, 10, 50)
    ),
    col = pal_discrete_sc
)
```

## Annotation
```{r, eval = FALSE, fig.height = 12}
singleR_fine <- readRDS(file.path(path, "singleR_fin_bcell.rds"))
for (x in unique(Idents(seurat)))
  plotScoreHeatmap(
    singleR_fine,
    labels.use = unique(seurat$cell_subtype_formatted),
    # annotation_legend = FALSE,
    cells.use = WhichCells(seurat, idents = x),
    color = colorRampPalette(brewer.pal(9, "Reds"))(100),
    # normalize = FALSE,
    max.labels = 10,
    # show.pruned = TRUE
  )
```

## Markers
### From dataset
```{r, message = FALSE}
data("jcb_markers")
plot_module(seurat, jcb_markers, cols = pal_discrete_sc)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
plot_markers(seurat, jcb_markers, cols = pal_discrete_sc)
```

### B cell markers
```{r, fig.height = 6, fig.width = 12}
data("l_bcell_markers")
plot_markers(seurat, l_bcell_markers, cols = pal_discrete_sc)
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
