---
title: "qc_integration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{qc_integration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/qc_integration/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

```{r}
library("GimmmeMySC")
library("GimmeMyPlot")
library("rlist")
library("cowplot")
library("kableExtra")
library("Seurat")

source(
  file.path(file.path(
  dirname(getwd()),
  "inst",
  "extdata"
), "conf.R"))

old_ident <- snn_cluster
new_ident <- snn_cluster
reorder_ident <- c("6", "1", "2", "0", "7", "3", "5", "4", "8", "9")
# old_ident <- "old_labels"
# new_ident <- "predicted.labels"
```

```{r}
load(file.path(path_data, paste0(seurat_dataset, ".rda")))

seurat$cell_subtype_formatted2 <- seurat$cell_subtype_formatted

seurat <- reorder_idents(seurat, new_ident)
levels(seurat) <- reorder_ident
seurat[[]][, "reorder_ident"] <- Idents(seurat)
new_ident <- "reorder_ident" -> snn_cluster -> old_ident

seurat_subset <- subsampling_sc(seurat)
plot_dim(seurat, cols = pal_discrete_sc)
```

```{r, fig.height = 2, fig.width = 2}
plot_dim(seurat, cols = pal_discrete_sc, alpha = .1, label.size = 8) + 
  NoLegend() +
  theme(
    plot.margin = unit(c(0, 0, 0, 0), "cm"),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )
```

```{r}
p2 <- plot_dim(seurat, cols = pal_discrete_sc)
p2

p2 + plot_dim_cell(seurat, group.by = "cell_subtype_formatted2", cols = pal_discrete_sc2)

p2 + plot_dim_cycle0(seurat) %>% pluck(1)
```

## UMAP per Type
```{r}
plot_dim(
  object = seurat_subset,
  split.by = 'Type',
  col = pal_discrete_sc
) + NoLegend()

bar_ident_group(
  seurat_subset, 
  group.by = "Type", 
  idents = snn_cluster
)

bar_group_ident(
  seurat,
  group.by = "Type",
  idents = snn_cluster,
  colour = pal_discrete_sc
)
```

## UMAP per Patient
```{r}
subsampling_sc(seurat, group.by = "Patient") %>%
  plot_dim(
    split.by = 'Patient',
    col = pal_discrete_sc,
    ncol = 2
  ) + NoLegend()

bar_ident_group(
  seurat, 
  group.by = "Patient", 
  idents = snn_cluster
)

bar_group_ident(
  seurat,
  group.by = "Patient",
  idents = snn_cluster,
  colour = pal_discrete_sc
)
```

## Annotation
```{r}
bar_group_ident(
    seurat,
    idents = "cell_subtype_formatted2",
    group.by = "Type",
    colour = pal_discrete_sc
)

Idents(seurat) <- "cell_subtype_formatted2"
plot_bar_sc(seurat)
Idents(seurat) <- snn_cluster

Idents(seurat_subset) <- "cell_subtype_formatted2"
plot_dim_cell(seurat_subset, split.by = "Type", col = pal_discrete_sc)
Idents(seurat_subset) <- snn_cluster
```

## Markers
```{r, message = FALSE, fig.height = 6, fig.width = 12}
data("l_bcell_markers2")
plot_marker_split(seurat, l_bcell_markers2)
plot_feature_split(seurat_subset, l_bcell_markers2, normalize = TRUE, cluster = TRUE)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
data("jcb_markers")
plot_marker_split(seurat, jcb_markers)
plot_feature_split(seurat_subset, jcb_markers, normalize = TRUE, cluster = TRUE)
```

## Cell per cluster
```{r}
seurat_subset <- subsampling_sc(seurat) %>%
  subset(subset = Type == target_type)
seurat <- subset(seurat, subset = Type == target_type)

seurat <- reorder_idents(seurat, old_ident)
plot_dim(
    seurat_subset, 
    split.by = old_ident,
    col = pal_discrete_sc,
    pt.size = .25,
    ncol = 4,
    label = FALSE
) + NoLegend()

Idents(seurat) <- new_ident
plot_dim(
    seurat_subset, 
    split.by = new_ident,
    col = pal_discrete_sc,
    pt.size = .25,
    ncol = 4,
    label = FALSE
) + NoLegend()
```

```{r, fig.height = 2, fig.width = 2}
tmp <- reorder_idents(seurat, y = old_ident)
plot_dim(tmp, cols = pal_discrete_sc, alpha = .1, label.size = 8) + 
    NoLegend() +
    theme(
        plot.margin = unit(c(0, 0, 0, 0), "cm"),
        axis.text = element_blank(),
        axis.ticks = element_blank()
    )
```
  
```{r}
plot_dim(tmp, cols = pal_discrete_sc)
seurat <- reorder_idents(seurat, new_ident)
plot_dim(seurat_subset, cols = pal_discrete_sc)
```

## Scores
```{r, eval = FALSE, message = FALSE, fig.height = 6, fig.width = 12}
plot_sc_violin(
    seurat,
    features = paste0("prediction.score.", levels(Idents(seurat))),
    nrow = 2,
    ncol = 5
)
```

## Confusing table
```{r, fig.width = 4.5}
confusing_table(seurat, new_ident = new_ident, old_ident = old_ident, as_percent = FALSE)
confusing_table(seurat, new_ident = new_ident, old_ident = old_ident, )
confusing_table(seurat, new_ident = new_ident, old_ident = old_ident, margin = 2)
```

## Cell markers
### From microarray
```{r, message = FALSE}
plot_module(seurat, jcb_markers)
```

```{r, message = FALSE, fig.height = 6, fig.width = 12}
plot_ident_celltype(seurat)
```

## Misclassified
```{r, message = FALSE, fig.height = 6, fig.width = 12}
l_seurat <- list.map(
    levels(Idents(seurat)),
    f(x) ~ {
      res <- subset(seurat, idents = x)
      Idents(res) <- old_ident
      return(res)
    }
)

p <- list.map(
    l_seurat,
    f(x, y, z) ~ plot_dim(x, pt.size = 1) +
      ggtitle(z)
)

plot_grid(plotlist = p, ncol = 3, nrow = 2, align = "hv")
plot_grid(plotlist = p[8:length(p)], ncol = 3, nrow = 2, align = "hv")
```

```{r}
tmp <- list.map(
    l_seurat,
    f(x, y, z) ~cluster_size(Idents(x))  %>%
     rbind("Total" = c(n = colSums(.[, "n", drop = FALSE]), freq = "")) %>% 
        rownames_to_column(var = "Group") %>%
        mutate(Cluster = z)
    ) %>%
     list_rbind()


cluster_counts <- tmp %>% 
  count(Cluster) %>% 
  pull(n)

group_names <- paste("Cluster", unique(tmp$Cluster))

p <- tmp %>% 
    select(-Cluster) %>%
    kable_sc()  %>%
  pack_rows(
    index = setNames(cluster_counts, group_names),
    label_row_css = "background-color: #666; color: #fff;"
  )
save_kable(
    p,
    file = file.path(path_fig, "table_cells.png"),
    zoom = 2
)
p
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
