---
title: "QC RNA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{qc_rna}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r config, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/qc_rna/",
  fig.width = 8,
  fig.height = 3.7,
  dpi = 300
)
```

## Setup
```{r}
library("GimmmeMySC")
library("GimmeMyPlot")
library("Seurat")
library("rlist")
library("scDblFinder")
library("DoubletFinder")
library("parallel")
library("BiocParallel")
library("kableExtra")
library("SoupX")
library("cowplot")
library("RColorBrewer")
library("viridis")

source(
  file.path(file.path(
  dirname(getwd()),
  "inst",
  "extdata"
), "conf.R"))

l_samples <- list.files(path_project) %>%  
  .[sapply(., function(x) dir.exists(file.path(path_project, x)))]
n_cores <- detectCores() - 1
soupex <- TRUE
doublet_method <- "doubletFinder"
```

## Load data
```{r data}
if (!isTRUE(soupex))
list_seurat <- list.map(
    l_samples,
    f(x) ~{
      count_matrix <- file.path(path_project, x, "outs") %>% 
        list.files(full.names = TRUE) %>% 
        .[str_detect(., "filtered_feature_bc_matrix.h5")]
      tmp <- Read10X_h5(count_matrix) %>%
      CreateSeuratObject() %>%
      set_percent()
    }
)
```

## Ambiant RNA
```{r}
if (isTRUE(soupex))
list_seurat <- list.map(
  l_samples,
  f(i) ~ {
    sc <- file.path(path_project, i, "outs") %>%
      load10X() %>%
      autoEstCont(doPlot = FALSE) %>%
      setDR(.$metaData[, c("tSNE1", "tSNE2")])
    spx <- adjustCounts(sc, roundToInt = TRUE) %>%
      CreateSeuratObject() %>%
      set_percent() %>%
      AddMetaData(metadata = sc$metaData)
    spx[["raw"]] <- CreateAssayObject(sc$toc)
    return(list(sc = sc, seurat = spx))
  }
)
```

```{r}
cell_id <- paste0(str_extract(l_samples, "(WT)|(KO)"), "_", str_remove_all(l_samples, "(WT)|(KO)"))

if (isTRUE(soupex)) {
  sc <- list.map(list_seurat, .$sc)
  list_seurat <- list.map(list_seurat, .$seurat)
}

seurat <- integrate_multisamples(list_seurat, cell_id)
seurat[["RNA"]] <- JoinLayers(seurat[["RNA"]])
```

### QC
```{r, fig.height = 7}
if (isTRUE(soupex)) {
  (sum(seurat[["RNA"]]@layers$counts) / sum(seurat[["raw"]]$counts)) %>% as.data.frame() %>%
  kable0() %>%
    save_kable(file.path(path_fig, "pct_change.png"), zoom = 2)
    
  list.map(sc, .$fit$rhoEst) %>%
    as.data.frame() %>%
    kable0()  %>%
    save_kable(file.path(path_fig, "pct_change_sample.png"), zoom = 2)
  
  before.data <- GetAssayData(seurat, layer = "counts", assay = "raw")
  before.data@x[before.data@x > 0] <- 1
  after.data <- GetAssayData(seurat, layer = "counts", assay = "RNA")
  after.data@x[after.data@x > 0] <- 1
  
  diff <- before.data - after.data
  
  changed <- (diff == 1) * 1
  markers <- Matrix::rowSums(changed) %>% 
    sort(decreasing = TRUE)
  
  markers %>% 
    head(20) %>%
    plot_bar(sample_size  = length(Cells(seurat)), title = "", cex = 0.8)
  
  sum_before <- Matrix::rowSums(before.data)
  
  markers_frac <- (sum_before - Matrix::rowSums(after.data))
  markers_frac2 <- markers_frac / ((sum_before + 1e-6)) * 100
  
  markers_frac2 %>% 
  sort(decreasing = TRUE) %>%
    head(35) %>%
    plot_bar(sample_size = 100, title = "", cex = 0.5)
  
  markers_frac %>% 
  sort(decreasing = TRUE) %>%
    head(35) %>%
    plot_bar(title = "", label_x  = "value", cex = 0.5)
  
  intersect(head(markers, 50) %>% names(), sort(markers_frac2, decreasing = TRUE) %>% head(50) %>% names())
}
```

```{r}
if (isTRUE(soupex)) {
  markers_selected <- markers %>% head(6) %>% names()
  tsne_matrix <- as.matrix(seurat@meta.data[, c("tSNE1", "tSNE2")])
  rownames(tsne_matrix) <- Cells(seurat)
  plot_feature_soupex(seurat, markers_selected, tsne_matrix, "raw")
}
```

```{r}
if (isTRUE(soupex)) {
  plot_feature_soupex(seurat, markers_selected, tsne_matrix, "RNA")
}
```

```{r}
if (isTRUE(soupex)) {
list.map(
  unique(seurat$Patient),
  f(x) ~ {
    cols <- unique(seurat$clusters) %>% length() %>% palette_continuous()(.)
plot_dim(
    seurat,
    group.by = "clusters",
    cells = WhichCells(seurat, expression = Patient == x),
    cols = cols,
    label = FALSE
) +
      ggtitle(x) +
  NoLegend()
  }
) %>% plot_grid(plotlist = ., ncol = 2)
}
```

```{r}
if (isTRUE(soupex)) {
cells <- Matrix::colSums(changed) %>% 
  sort(decreasing = TRUE) %>%
  names()

list.map(
  unique(seurat$Patient),
  f(x) ~ {
    cell2 <- WhichCells(seurat, expression = Patient == x)
intersect(cell2, cells) %>%
  head(5e2) %>%
  plot_dim_selected(seurat, selected = ., cells = cell2) +
      ggtitle(x)
  }) %>% 
  plot_grid(plotlist = ., ncol = 2)
}
```

```{r, fig.width = 8, fig.height = 3.7}
if (isTRUE(soupex)) {
  list.map(
    names(markers)[seq(10)],
    f(x) ~{
  list.map(
    unique(seurat$Patient),
    f(i) ~ {
  p <- plotChangeMap(
      sc[[i]], 
      list_seurat[[i]][["RNA"]]$counts,
      x,
      pointSize  = 0.5
    ) + scale_color_gradientn(colors = viridis(100)) +
      ggtitle(i)
    theme_sc_dim(p)
      }
    ) %>% plot_grid(plotlist = ., ncol = 2) %>%
              plot_grid(
                ggdraw() + 
                  draw_label(
                    x,
                    color = "#2F5496",
                    size = 20,
                    fontface = "bold.italic"
                  ),
                .,
                ncol = 1,
                rel_heights = c(0.1, 1)
              )
    }
  )
}
```


## Filter cells with low or too high genes
```{r qc_plot, fig.height = 5, fig.width = 10}
plot_mqc(seurat, file = file.path(path_fig, "table_stats.png"))
```

```{r}
seurat_old <- seurat
features <- c("nFeature_RNA", "nCount_RNA", "percent_mitochondrial")
list_seurat <- list_seurat %>%
  list.map(
    f(i) ~{
      stats_qc <- sapply(
        features,
        function(x) quantile(
            i[[x]], 
            probs = c(0, .025, .05, .1, seq(.25, .75, .25), .9, .95, .975, 1), 
            na.rm = TRUE)
    )
    subset(
      i, 
      subset = 
        nFeature_RNA > stats_qc["10%", "nFeature_RNA"] &
        nFeature_RNA < stats_qc["90%", "nFeature_RNA"] & 
        percent_mitochondrial < stats_qc["90%", "percent_mitochondrial"] & 
        nCount_RNA < stats_qc["90%", "nCount_RNA"]
  )
  }
)
```

## Doublets
### DoubletFinder
```{r}
multiplet_rates_10x <- data.frame(
  multiplet_rate = c(0.004, 0.008, 0.0160, 0.023, 0.031, 0.039, 0.046, 0.054, 0.061, 0.069, 0.076),
  recovered_cells = c(500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000)
)

if (.Platform$OS.type == "windows") {
    n_cores2 <- 1
} else {
    n_cores2 <- n_cores
}

list_seurat <- list.map(
    list_seurat,
    f(i) ~{
        if (isFALSE(SCT)) {
          i <- NormalizeData(i) %>%
            FindVariableFeatures() %>%
            ScaleData() %>%
            RunPCA(npcs = max_dim)
        }
        doublet_finder <- paramSweep(i, PCs = seq(n_dim), sct = SCT, num.cores = n_cores2)
        
        doublet_finder_stats <- summarizeSweep(doublet_finder)
        doublet_finder_best <- find.pK(doublet_finder_stats)
        
        pK <- doublet_finder_best %>%
            filter(BCmetric == max(BCmetric)) %>%
            pull(pK) %>%
            as.character() %>%
            as.numeric()
        
        multiplet_rate <- multiplet_rates_10x %>% 
            filter(recovered_cells < nrow(i@meta.data)) %>% 
            dplyr::slice(which.max(recovered_cells)) %>%
            select(multiplet_rate) %>%
            as.character() %>%
            as.numeric()
        nExp <- round(multiplet_rate * nrow(i@meta.data))
        
        homotypic.prop <- modelHomotypic(i$clusters)
        nExp_adj <- round(nExp * (1 - homotypic.prop))
        
        i <- doubletFinder(
            i,
            PCs = seq(n_dim),
            pK = pK, 
            nExp = nExp_adj,
            sct = SCT
        )
        doublet_name <- paste(0.25, pK, nExp_adj, sep = "_")
        i@meta.data <- i@meta.data %>% 
            rename_with(
                ~"doubletFinder", 
                all_of(paste0("DF.classifications_", doublet_name))
            ) %>%
            rename_with(
                ~"pANN", 
                all_of(paste0("pANN_", doublet_name))
            )
        
        gc()
        return(i)
    }
)
seurat <- integrate_multisamples(list_seurat, cell_id)
```

### scDblFinder
```{r}
seurat[["RNA"]] <- JoinLayers(seurat[["RNA"]])

if (.Platform$OS.type == "windows") {
  bp_param <- SnowParam(workers = n_cores, type = "SOCK",  exportglobals = TRUE, progressbar = TRUE)
} else {
  bp_param <- MulticoreParam(workers = n_cores, progressbar = TRUE)
}

sce <- scDblFinder(
  GetAssayData(seurat[["RNA"]], layer = "counts"),
  samples = seurat$Patient,
  aggregateFeatures = FALSE,
  k = NULL,
  processing = "normFeatures",
  dims = 20,
  cluster = as.factor(seurat$clusters),
  BPPARAM = bp_param
)

seurat$scDblFinder <- sce[, row.names(seurat[[]])]$scDblFinder.class %>% str_to_sentence()
seurat$doublet_score <- sce[, row.names(seurat[[]])]$scDblFinder.score
```

### QC
```{r, fig.height = 8}
kable_doublet(seurat, file = file.path(path_fig, "table_doublets_scDblFinder.png"))

plot_bar_doublet(seurat)
```

```{r}
plot_violin_doublet <- function(x) plot_sc_violin(x, features = "doublet_score", ncol = 1, nrow = 1)
Idents(seurat) <- "scDblFinder"
plot_violin_doublet(seurat)
Idents(seurat) <- "Patient"
plot_violin_doublet(seurat)
```

```{r, fig.height = 8}
kable_doublet(seurat, label = "doubletFinder", file = file.path(path_fig, "table_doublets_doubletFinder.png"))

plot_bar_doublet(seurat, label = "doubletFinder")
```

```{r}
plot_violin_doublet <- function(x) plot_sc_violin(x, features = "pANN", ncol = 1, nrow = 1)

Idents(seurat) <- "doubletFinder"
plot_violin_doublet(seurat)
Idents(seurat) <- "Patient"
plot_violin_doublet(seurat)
```

```{r}
df <- select(seurat[[]], scDblFinder, doubletFinder)
pivot_longer(
      df,
      cols = everything(),
      names_to = "groupe",
      values_to = "Group"
    ) %>% 
    relocate(Group) %>%
    plot_bar_2cat(stats = FALSE, legend = c("Singlet", "Doublet"))
plot_alluvial(df)

table(seurat$scDblFinder, seurat$doubletFinder) %>%
    as.data.frame.matrix() %>%
    kable() %>%
    pack_rows("scDblFinder", 1, 2) %>%
    add_header_above(c(" " = 1, "DoubletFinder" = 2)) %>%
    kable_styling(full_width = FALSE) %>%
    save_kable(
        file = file.path(path_fig, "table_scdblFinder_doubletFinder.png"),
        zoom = 2
    )
```

```{r}
if (isTRUE(soupex)) {
list.map(
  unique(seurat$Patient),
  f(x) ~ {
    selected <- WhichCells(seurat, expression = scDblFinder == "Doublet" & doubletFinder == "Doublet")
    cells <- WhichCells(seurat, expression = Patient == x)
intersect(selected, cells) %>%
  plot_dim_selected(seurat, selected = ., cells = cells) +
      ggtitle(x)
  }) %>% 
  plot_grid(plotlist = ., ncol = 2)
}
```

```{r}
if (!isFALSE(doublet_method))
  seurat <- seurat[, seurat[[doublet_method]][,1] == "Singlet"]
```

## Gene filtering
```{r filter_mark}
if (isFALSE(SCT)) {
      seurat <- NormalizeData(seurat) %>%
      FindVariableFeatures()
    variable_plot(seurat)
}
```

## PCA
```{r pca}
if (!SCT) {
  if (assay == "sketch") {
    seurat <- SketchData(seurat, over.write = TRUE)
    DefaultAssay(seurat) <- "sketch"
  }
  seurat <- ScaleData(seurat)
} else {
  seurat[["RNA"]] <- split(
      seurat[["RNA"]],
      f = seurat[[]][, split.by],
      layers = c("counts", "data")
  )
  seurat <- SCTransform(seurat, method = "glmGamPoi", assay = "RNA")
  if (assay == "sketch") {
     seurat <- SketchData(seurat, over.write = TRUE)
    DefaultAssay(seurat) <- "sketch"
  }
}
seurat <- RunPCA(seurat, reduction_key = "Dim. ", npcs = max_dim)
```

## QC after
```{r qc_sub, fig.height = 8}
(ncol(seurat) / ncol(seurat_old) * 100 - 100) %>% `*`(-1) %>% round(1) %>% paste("%")

plot_bar_kept(seurat_old, seurat, unique(seurat$Patient))
```

## Save data
```{r}
save(seurat, file = file.path(path_data, paste0(seurat_dataset, ".rda")))
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
